name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs: 
  build-and-deploy: #nome da tarefa
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web
      with:
        working-directory: ./web

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Yarn Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy Storybook
        run: yarn deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}